### ISSUE TITLE
Hide "follow button" for logged user when they're on their own accounts

### ISSUE THREAD

**Issue by arkhurst** [Bendomey/project-mfoni#119]
<img width="1490" alt="image" src="https://github.com/user-attachments/assets/fd5108b4-d5c3-49c1-a008-2feafd37e5b5">

**Comment by Bendomey** [comment]
I just remembered. we can remove it entirely. We now have a new page for creator pages (https://mfoni.fly.dev/@fiifi). So /account is always private to the user logged in.

Work Items:
- Remove follow
- Share button should be dynamically rendered. `user.Role === "CREATOR"` should only see this button

**Comment by arkhurst** [comment]
Cool stuff, nice catchm thanks!
